### ISSUE TITLE
How to load Lidar point cloud, No function for LoadPointsFromFile_DeepAccident

### ISSUE THREAD

**Issue by abhishekjagtap1** [tianqi-wang1996/DeepAccident#11]
Code Snippet from DeepAccident_single_frame_tiny_v2x.py
train_pipeline = [
    # load image and apply image-view augmentation
    dict(type='LoadMultiViewImageFromFiles_DeepAccident', using_ego=True, temporal_consist=True,
         is_train=True, data_aug_conf=data_aug_conf),
    # load 3D bounding boxes & bev-semantic-maps
    dict(type='LoadAnnotations3D_MTL', with_bbox_3d=True,
         with_label_3d=True, with_instance_tokens=True),

I want to do or add something like this for loading the point cloud
dict(
        type='LoadPointsFromFile',
        coord_type='LIDAR',
        load_dim=6,
        use_dim=5,),

**Comment by abhishekjagtap1** [comment]
No problem, Solved it thanks

**Comment by aidana-ist** [comment]
how did you solve it
