### ISSUE TITLE
Questions about training models

### ISSUE THREAD

**Issue by BITwtz** [tianqi-wang1996/DeepAccident#18]
When performing the task of training the model, I always get stuck in the position of the picture
![image](https://github.com/tianqi-wang1996/DeepAccident/assets/153470867/c2a21ed1-18dd-471e-874e-24bbe54132d3)

**Comment by BITwtz** [comment]
The issue is resolved with the cuda version

**Comment by wangyy0** [comment]
Hi, I meet the same question. Which version of cuda are you using?

**Comment by wangyy0** [comment]
> The issue is resolved with the cuda version

Hi, I meet the same question. Which version of cuda are you using?
