### ISSUE TITLE
0 mAP Problem

### ISSUE THREAD

**Issue by BITwtz** [tianqi-wang1996/DeepAccident#23]
Thank you very much for your work, I found poor results in the testing phase, as follows:
Overall mAP:
0.0000

other part cost 0.55289 s
{'pts_bbox/CARLA/car_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/car_mATE': 1.0, 'pts_bbox/CARLA/car_mASE': 1.0, 'pts_bbox/CARLA/car_mAOE': 1.0, 'pts_bbox/CARLA/car_mAVE': 1.0, 'pts_bbox/CARLA/truck_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/truck_mATE': 1.0, 'pts_bbox/CARLA/truck_mASE': 1.0, 'pts_bbox/CARLA/truck_mAOE': 1.0, 'pts_bbox/CARLA/truck_mAVE': 1.0, 'pts_bbox/CARLA/van_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/van_mATE': 1.0, 'pts_bbox/CARLA/van_mASE': 1.0, 'pts_bbox/CARLA/van_mAOE': 1.0, 'pts_bbox/CARLA/van_mAVE': 1.0, 'pts_bbox/CARLA/cyclist_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/cyclist_mATE': 1.0, 'pts_bbox/CARLA/cyclist_mASE': 1.0, 'pts_bbox/CARLA/cyclist_mAOE': 1.0, 'pts_bbox/CARLA/cyclist_mAVE': 1.0, 'pts_bbox/CARLA/motorcycle_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/motorcycle_mATE': 1.0, 'pts_bbox/CARLA/motorcycle_mASE': 1.0, 'pts_bbox/CARLA/motorcycle_mAOE': 1.0, 'pts_bbox/CARLA/motorcycle_mAVE': 1.0, 'pts_bbox/CARLA/pedestrian_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/pedestrian_mATE': 1.0, 'pts_bbox/CARLA/pedestrian_mASE': 1.0, 'pts_bbox/CARLA/pedestrian_mAOE': 1.0, 'pts_bbox/CARLA/pedestrian_mAVE': 1.0, 'pts_bbox/CARLA/Overall_3D_mAP': 0.0}

**Comment by Hongbo123467** [comment]
I have the same question，the test result is confusing，how did you solve it？

**Comment by Kevin020503** [comment]
> Thank you very much for your work, I found poor results in the testing phase, as follows: Overall mAP: 0.0000
> 
> other part cost 0.55289 s {'pts_bbox/CARLA/car_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/car_mATE': 1.0, 'pts_bbox/CARLA/car_mASE': 1.0, 'pts_bbox/CARLA/car_mAOE': 1.0, 'pts_bbox/CARLA/car_mAVE': 1.0, 'pts_bbox/CARLA/truck_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/truck_mATE': 1.0, 'pts_bbox/CARLA/truck_mASE': 1.0, 'pts_bbox/CARLA/truck_mAOE': 1.0, 'pts_bbox/CARLA/truck_mAVE': 1.0, 'pts_bbox/CARLA/van_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/van_mATE': 1.0, 'pts_bbox/CARLA/van_mASE': 1.0, 'pts_bbox/CARLA/van_mAOE': 1.0, 'pts_bbox/CARLA/van_mAVE': 1.0, 'pts_bbox/CARLA/cyclist_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/cyclist_mATE': 1.0, 'pts_bbox/CARLA/cyclist_mASE': 1.0, 'pts_bbox/CARLA/cyclist_mAOE': 1.0, 'pts_bbox/CARLA/cyclist_mAVE': 1.0, 'pts_bbox/CARLA/motorcycle_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/motorcycle_mATE': 1.0, 'pts_bbox/CARLA/motorcycle_mASE': 1.0, 'pts_bbox/CARLA/motorcycle_mAOE': 1.0, 'pts_bbox/CARLA/motorcycle_mAVE': 1.0, 'pts_bbox/CARLA/pedestrian_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/pedestrian_mATE': 1.0, 'pts_bbox/CARLA/pedestrian_mASE': 1.0, 'pts_bbox/CARLA/pedestrian_mAOE': 1.0, 'pts_bbox/CARLA/pedestrian_mAVE': 1.0, 'pts_bbox/CARLA/Overall_3D_mAP': 0.0}

I have the same question, can you tell me your solution?
![image](https://github.com/tianqi-wang1996/DeepAccident/assets/74125029/5aaf36bf-af26-480c-8f39-483122351ebb)
