### ISSUE TITLE
The error of evaluation

### ISSUE THREAD

**Issue by LuPaoPao** [tianqi-wang1996/DeepAccident#4]
Thank you very much for your excellent work. I followed the steps you recommended to repeat, but the evaluation results are very bad:
Overall mAP:
0.0175
other part cost 12.22858 s
{'pts_bbox/CARLA/car_3D_average_distance_mAP': 0.105, 'pts_bbox/CARLA/car_mATE': 1.0, 'pts_bbox/CARLA/car_mASE': 1.0, 'pts_bbox/CARLA/car_mAOE': 1.0, 'pts_bbox/CARLA/car_mAVE': 1.0, 'pts_bbox/CARLA/truck_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/truck_mATE': 1.0, 'pts_bbox/CARLA/truck_mASE': 1.0, 'pts_bbox/CARLA/truck_mAOE': 1.0, 'pts_bbox/CARLA/truck_mAVE': 1.0, 'pts_bbox/CARLA/van_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/van_mATE': 1.0, 'pts_bbox/CARLA/van_mASE': 1.0, 'pts_bbox/CARLA/van_mAOE': 1.0, 'pts_bbox/CARLA/van_mAVE': 1.0, 'pts_bbox/CARLA/cyclist_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/cyclist_mATE': 1.0, 'pts_bbox/CARLA/cyclist_mASE': 1.0, 'pts_bbox/CARLA/cyclist_mAOE': 1.0, 'pts_bbox/CARLA/cyclist_mAVE': 1.0, 'pts_bbox/CARLA/motorcycle_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/motorcycle_mATE': 1.0, 'pts_bbox/CARLA/motorcycle_mASE': 1.0, 'pts_bbox/CARLA/motorcycle_mAOE': 1.0, 'pts_bbox/CARLA/motorcycle_mAVE': 1.0, 'pts_bbox/CARLA/pedestrian_3D_average_distance_mAP': 0.0, 'pts_bbox/CARLA/pedestrian_mATE': 1.0, 'pts_bbox/CARLA/pedestrian_mASE': 1.0, 'pts_bbox/CARLA/pedestrian_mAOE': 1.0, 'pts_bbox/CARLA/pedestrian_mAVE': 1.0, 'pts_bbox/CARLA/Overall_3D_mAP': 0.0175}
[20230503_212425.log](https://github.com/tianqi-wang1996/DeepAccident/files/11471052/20230503_212425.log)

Here is the log of training:

[20230503_212425.log](https://github.com/tianqi-wang1996/DeepAccident/files/11471053/20230503_212425.log)

By the way, through the visualization you gave, I did not predict any box here.

**Comment by tianqi-wang1996** [comment]
Sorry for the inconvience caused, I checked the documents that I provide and it turns out that I miss some instructions.

I have updated the [data_preparation.md](https://github.com/tianqi-wang1996/DeepAccident/blob/main/docs/data_preparation.md) and [getting_started.md](https://github.com/tianqi-wang1996/DeepAccident/blob/main/docs/getting_started.md). You should download the pretrained weights of Swin-Transformer and BEVerse and put them in the dataset root (./data/DeepAccident_data) to initialize training.

Then when you start training, add this --load-from option. 
For multiple gpus:
```bash
 bash tools/dist_train.sh projects/configs/DeepAccident_tiny.py 8 --load-from ./data/DeepAccident_data/beverse_tiny.pth --work-dir work_dirs/DeepAccident_tiny
```
For single gpu:
```bash
python tools/train.py projects/configs/DeepAccident_tiny.py --load-from ./data/DeepAccident_data/beverse_tiny.pth --work-dir work_dirs/DeepAccident_tiny
```

**Comment by LuPaoPao** [comment]
Thank you for your reply. I directly reasoned with the model you gave and got the correct result. I tried to use the swim model of pre-training to train. Thank you very much
![图片](https://github.com/tianqi-wang1996/DeepAccident/assets/36125195/d5020a54-a124-4ff0-958c-651d5fa52bc8)

**Comment by WangzcBruce** [comment]
Excuse me, bro, when you run the  【python tools/train.py projects/configs/DeepAccident_tiny.py --load-from ./data/DeepAccident_data/beverse_tiny.pth --work-dir work_dirs/DeepAccident_tiny
】, have you met the error that【 TypeError: simple_test() got an unexpected keyword argument 'gt_bboxes_3d'】
![image](https://github.com/tianqi-wang1996/DeepAccident/assets/45158420/df02421d-a88d-4c23-a303-ed1197c5fb2b)
the unexpected keyword from test_pileline 
![image](https://github.com/tianqi-wang1996/DeepAccident/assets/45158420/0186618d-56c2-40ff-9662-0e967bd382f3)
